### ISSUE TITLE
The Tiled and the script editor

### ISSUE THREAD

**Issue by Drakaroft** [RobinPerris/DarkUI#1]
Hi i have compiled the project and it is really awesome, now i want to try to costumize the title bar and the border for get the best UI.
But i want to ask another thing, i see a tiled editor and a script editor in the screen but they aren't in the project exist a repository where i can found them?

**Comment by RobinPerris** [comment]
The idea of this project is a stand-alone control docking system that isn't limited to specific uses. My game editor isn't really related to that.

The things you listed are just standard form controls like any other. To do something similar, just create a 'DarkDocument' with a control set to 'Dock - Fill' and load it in to the dock panel. It'll have the same effect.

For the script editor I used a modified version of this control: https://www.codeproject.com/Articles/161871/Fast-Colored-TextBox-for-syntax-highlighting

For the map editor, I created something custom that's heavily tied in to my game editor project and isn't something I can really release stand-alone. I used SFML and set it up to render to a control handle instead of an OpenGL window. I then tied the 'Paint' method of the user control to trigger a re-render of the SFML graphics.

Everything else are just standard programming patterns - undo/redo, for example, is just a very simple 'Command Pattern' implementation.

**Comment by Drakaroft** [comment]
Ok, thanks!
Just another thing, why i don't find the radio button ecc in the strument box? I have tryied adding the dll but still don't work :(

**Comment by RobinPerris** [comment]
Follow this article from the project wiki: https://github.com/RobinPerris/DarkUI/wiki/Using-DarkUI

**Comment by Drakaroft** [comment]
Stupid me i was forgetting to put DarkUI in the reference for this i was unable to get the components ahahah, thanks man!

**Comment by RobinPerris** [comment]
No problem. Enjoy using the library!
