### ISSUE TITLE
No DarkComboBox

### ISSUE THREAD

**Issue by merthsoft** [RobinPerris/DarkUI#15]
When I get the package form NuGet, there's a DarkComboBox control. However, this control isn't found in the repository.

**Comment by RobinPerris** [comment]
~I never published this library to NuGet. Are you sure this is the library you're using, rather than another with a similar name?~

Nevermind, just saw your other issue. You are certainly using this library. It looks like someone else decided to publish it to NuGet.

In regards to the control not showing up - do you mean in the Toolbox when using the Visual Studio visual designer? If so, you might need to follow the steps in this Wiki page:
https://github.com/RobinPerris/DarkUI/wiki/Using-DarkUI

**Comment by merthsoft** [comment]
Oh, I see, that's someone else's upload of your library. Very weird. You should kick them off and upload it yourself!

In any case, I can find the control in the library itself, just not in this repo to look at the code. Maybe the other person added their own controls as well?

**Comment by merthsoft** [comment]
Looking at the dll from nuget, it looks like the following three controls are in that library and not the one in git. I assume they were added by the cloner?

`DarkComboBox`
`DarkGroupBox`
`DarkNumericUpDown`

**Comment by RobinPerris** [comment]
Ah, I see now. You're right, I never developed those controls. It looks like the owner of the NuGet repository added them. I'd suggest messaging him directly to get a copy of the forked code.

**Comment by RobinPerris** [comment]
Quick update: I got in touch and it turns out the NuGet version is published for use in a game development engine called Orion. However, it is unsupported and has known bugs.

You can check out the code here if you need it: https://github.com/AscensionGameDev/DarkUI

**Comment by merthsoft** [comment]
Oh awesome thanks so much!

**Comment by ParchmentWolf** [comment]
I kill it with fire D: <

**Comment by RobinPerris** [comment]
@merthsoft I've got a pull request to add this functionality to the library. Can you check out https://github.com/RobinPerris/DarkUI/pull/19 and see if this is what you need?
