### ISSUE TITLE
New Control : DarkDataGridView

### ISSUE THREAD

**Issue by ohhsodead** [RobinPerris/DarkUI#21]
Hi again!

Good work on your update, everything seems to function perfectly for me. Although, a dark dgv control is missing but is included in the forks I'm using. It's used heavily in my project so will have issues. Is there a chance you'd consider implementing this too?

Thanks.

**Comment by RobinPerris** [comment]
Can you link me to the fork? I'll take a look

**Comment by ohhsodead** [comment]
So, I can't find the fork anywhere. I think it has been removed from github, or wherever. I could create a repo with this project if you like, or can upload elsewhere (dropbox) to be downloaded for yourself.

**Comment by RobinPerris** [comment]
If you've got a local copy then pushing it to GitHub will allow me to take a look. If it's just a couple of files a gist would be fine too

**Comment by ohhsodead** [comment]
I've uploaded the project to a repo [here](https://github.com/ohhsodead/DarkUI-master) for you.

**Comment by biotech7** [comment]
hi，@RobinPerris  @ohhsodead，  thanks for your contributions, it's a great work.
 i have one question: could the gdv module be included in the dockcontent? i tried, but failed, could you help me figure out the problem？i am a novice。
![show steps](https://user-images.githubusercontent.com/49674341/77898574-ef6c9200-72ad-11ea-9586-e46ca661e285.jpg)

**Comment by ohhsodead** [comment]
@biotech7 Hello! I don't think this version of the project includes the dgv control, so I doubt @RobinPerris will know for sure.

**Comment by biotech7** [comment]
Hi,@ohhsodead, i have added it manually, but not fully tested.  thanks for your sharing.

**Comment by RobinPerris** [comment]
I realise it's been a while since this was posted, but I downloaded and played with this control a bit. What has been done so far is impressive, however there are some pretty big holes in the implementation that I'd need to fill before I'd be comfortable publishing this as part of the main DarkUI library.

Due to the fact I no longer use DarkUI for my own projects, I wouldn't have the time to maintain this control nor deal with any issues people raise when attempting to use it (as highlighted by Biotech's issue above).

If you're comfortable continuing to use that fork locally then that's fine. If you'd prefer to have it in a NuGet package I'd recommend packaging it up as a stand-alone extension and publishing it yourself. Something like `DarkUI.DataGridView` or the like.

Thanks for fishing it out and sharing the repo though, it's appreciated.
