### ISSUE TITLE
Error al querer colocar un ToolStrip en el formulario.

### ISSUE THREAD

**Issue by MauroArgentino** [RobinPerris/DarkUI#34]
Les comentó, estoy intentando hacer una aplicación. Descargué el proyecto DarkUI, pero como no tengo el entorno de desarrollo de Visual Studio 2017 y no tengo intenciones de instalarlo, estoy trabajando con SharpDevelop 5.1
El tema es así, en un momento, logré compilar el proyecto DarkUI.. y utilizar la DLL para agregar controles y demás, pero después, por alguna razón comenzó a arrojar errores, y ahora no me deja agregar controles o me tira errores en el proyecto por muestra errores relacionados a referencia a imágenes incrustadas que dice no encontrarlas o algo así.
Estuve queriendo además, agregar más formularios como el OpenFileDialog o cosas así, pero esto me está quebrando la cabeza, porque ya descargué los Microsoft Build Tools 2013 y 2015 y sigue haciendo lo mismo.
Aclaro, para poder abrir el proyecto DarkUI en SharpDevelop tuve que hacer algunas modificaciones.. pero lo había hecho funcionar.
Ahora no se exactamente qué es lo que está ocurriendo.
No se si es problema del SDK o que..
Necesitaría que alguien me pudiera dar una ayuda..

**Comment by RobinPerris** [comment]
I ran your comment through Google Translate. This is the result:

> He commented, I am trying to make an application. I downloaded the DarkUI project, but since I don't have Visual Studio 2017 development environment and have no intention of installing it, I am working with SharpDevelop 5.1
The issue is like this, at one point, I managed to compile the DarkUI project .. and use the DLL to add controls and so on, but then for some reason it started throwing errors, and now it won't let me add controls or it throws errors at the project by shows errors related to reference to embedded images that says not to find them or something like that.
I was also wanting to add more forms like OpenFileDialog or things like that, but this is breaking my head, because I already downloaded the Microsoft Build Tools 2013 and 2015 and it continues to do the same.
I clarify, in order to open the DarkUI project in SharpDevelop I had to make some modifications .. but I had made it work.
Now I don't know exactly what is happening.
I don't know if it's a problem with the SDK or what ...
I would need someone to help me.

It sounds like you're attempting to use DarkUI in SharpDevelop and haven't been able to get it working.

SharpDevelop is **discontinued** and **unsupported** (as shown on the [wiki page](https://en.wikipedia.org/wiki/SharpDevelop)). If SharpDevelop is throwing errors, it's almost certainly due to limitations on their form designer, not a problem with DarkUI or the .NET compiler.

Honestly, if you want to use WinForms for designing your applications, the latest version of Visual Studio is basically a requirement. WinForms as a technology is legacy at this point and really should not be used in new projects.

If you do not want to use Visual Studio 2019, I'd recommend either [VS Code](https://code.visualstudio.com/) or [JetBrains Rider](https://www.jetbrains.com/rider/). These are the tools I personally use to develop cross-platform .NET applications using dotnet core.

Instead of using DarkUI with WinForms, you should use a cross-platform modern GUI library such as [AvaloniaUI](https://github.com/AvaloniaUI/Avalonia) or [Eto](https://github.com/picoe/Eto).

If you wish to continue using WinForms and SharpDevelop that's fine too, but I won't be able to offer any support.
